services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.example.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://polyphonous-raegan-dowdily.ngrok-free.dev/
    volumes:
      - ./n8n_data:/home/node/.n8n
